### ISSUE TITLE
Logo with a very short claim gets cut off

### ISSUE THREAD

**Issue by wp99cp** [cevi/logo-generator#16]
If you try to create a logo with a very short claim, e.g. "GLK1" (left) and "2022" (right) the logo gets cut off. It seems that the width of the created image depends on the claim-width instead of the max (claim-with, logoBoxWidth).

Probably somewhere here:
https://github.com/cevi/logo-generator/blob/413200ed9897148604ae8dad672a75a16af6b207/src/js/Components/Logo/index.js#L110

![image](https://user-images.githubusercontent.com/34008738/166112861-a760b11e-5533-4669-9e22-ab809e2c4bb0.png)

**Comment by btemperli** [comment]
Thank you @wp99cp for reporting this bug.

It should be fixed now: [logo.cevi.ch](https://logo.cevi.ch/?logo-left=CEVI%20REGION&logo-right=Z%C3%9CRICH&logo-right-second=&claim-left=GLK%201&claim-right=%202022&color=web)

Can you please check it and close the ticket?

**Comment by wp99cp** [comment]
> Thank you @wp99cp for reporting this bug.
> 
> It should be fixed now: [logo.cevi.ch](https://logo.cevi.ch/?logo-left=CEVI%20REGION&logo-right=Z%C3%9CRICH&logo-right-second=&claim-left=GLK%201&claim-right=%202022&color=web)
> 
> Can you please check it and close the ticket?

Thank's, tested it and it seems to work!
