### ISSUE TITLE
Add Option to Create "Grundschrift Titelbalken"

### ISSUE THREAD

**Issue by wp99cp** [cevi/logo-generator#17]
Currently, it's only possible to create Claims with this Repo. An option to create _Titelbalken_ as well, would be nice!

![Screenshot from 2022-07-04 14-28-26](https://user-images.githubusercontent.com/34008738/177154943-49189a92-1dd9-46fc-9c19-234744d86f86.png)

## Possible use case

- https://github.com/wp99cp/responsive_images_for_jekyll

**Comment by btemperli** [comment]
Thank you for the initiative, sounds this is a good next feature!

At the moment I'm preparing a server-based image generator, with this you should be able to get the images directly by the api.

I will put this on the time-line for the upcoming tasks.

**Comment by btemperli** [comment]
Hey @wp99cp 

I just tried to fix this and I think, there is no fix needed. You can create this already: https://logo.cevi.ch/?logo-left=UND%20PL%C3%96TZLICH%20SCHNEITS&logo-right=&logo-right-second=&claim-left=WINTERSPASS&claim-right=%20PUR%20IN%20MADRUNS&color=black

Just leave the "Logo Rechts"-Textbox empty and no Logo will be created for the claim.

Does this help?

**Comment by btemperli** [comment]
Nevertheless, probably we should improve the usability and give the users the hint to leave the textboxes empty.
A second useful option would be to add images as background with the claim in the foreground. I will create a new ticket for that.

**Comment by wp99cp** [comment]
> Hey @wp99cp
> 
> I just tried to fix this and I think, there is no fix needed. You can create this already: https://logo.cevi.ch/?logo-left=UND%20PL%C3%96TZLICH%20SCHNEITS&logo-right=&logo-right-second=&claim-left=WINTERSPASS&claim-right=%20PUR%20IN%20MADRUNS&color=black
> 
> Just leave the "Logo Rechts"-Textbox empty and no Logo will be created for the claim.
> 
> Does this help?

Thank I missed that feature!
